### ISSUE TITLE
Title's text becomes blurry

### ISSUE THREAD

**Issue by shinywong** [valinet/WinCenterTitle#2]
Title's text becomes blurry after applying WinCenterTitle. You will notice it if the Title's text is long enough.

Before:

![Before](https://user-images.githubusercontent.com/10369132/93550199-7d901e00-f99d-11ea-9e94-5bccced94c47.png)

After:

![After](https://user-images.githubusercontent.com/10369132/93550232-897be000-f99d-11ea-8da3-6db8450890ca.png)

The center of the text is NOT blurry. The farther from the center, the text becomes more blurry.

**Comment by valinet** [comment]
I think this may happen due to line 36: `lprc->right -= 2;` in the source code. Try commenting that out, recompile and check if it helps. That is there so it fixes another problem, that the title rectangle sometimes overlaps the window ever so slightly, but maybe this is not an appropriate fix after all and we should look into coming up with another solution.

**Comment by valinet** [comment]
New version employs different (and more proper) method of centering the text, so `DrawTextW` is not hooked anymore, so this should not happen anymore; thus, I am closing this issue as the problem has been fixed indirectly.
